name: Deploy to cPanel via SSH

on:
  push:
    branches:
      - main # Atau branch yang ingin Anda deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.CPANEL_SSH_USERNAME }}@${{ secrets.CPANEL_SSH_HOST }} "
            cd /path/to/your/webroot; # Ganti dengan path webroot Anda
            git pull origin main;      # Atau branch yang sesuai
            # Tambahkan perintah build atau migrasi lainnya jika perlu
          "
